#!/bin/bash

date '+%F %H:%M:%S'

if [ -f "/opt/dlptrade/bg_updater_running" ]
then
    exit 0
fi

touch /opt/dlptrade/bg_updater_running
php /var/www/html/.htsend.php
rm -f /opt/dlptrade/bg_updater_running

